/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface HistoryData {
    id?: number;

    toothOrGumBleeding?: number;

    hematuria?: number;

    gIbleeding?: number;

    menorrhagia?: number;

    bleedingAfterOperations?: number;

    bleedingAfterTrauma?: number;

    bleedingAtbirth?: number;

    bleedingAfterVaccination?: number;

    jointBleeding?: number;

    skinBleeding?: number;

    muscleBleeding?: number;

    epistaxis?: number;

    familyHistoryOfBleedingDisorder?: number;

    motherCousin?: number;

    motherGrandfather?: number;

    motherGrandMother?: number;

    motherUncle?: number;

    motherAunt?: number;

    fatherCousin?: number;

    fatherGrandfather?: number;

    fatherGrandMother?: number;

    fatherUncle?: number;

    fatherAunt?: number;

    otherFamilyMembers?: number;

    maternalHistoryOfAbortion?: number;

    familyHistoryOfDeathDueToBleeding?: number;

    patientId?: number;

    userId?: number;

}
