/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export class History {
    id?: number;

    toothOrGumBleeding?: boolean = false;

    hematuria?: boolean = false;

    gIbleeding?: boolean = false;

    menorrhagia?: boolean = false;

    bleedingAfterOperations?: boolean = false;

    bleedingAfterTrauma?: boolean = false;

    bleedingAtbirth?: boolean = false;

    bleedingAfterVaccination?: boolean = false;

    jointBleeding?: boolean = false;

    skinBleeding?: boolean = false;

    muscleBleeding?: boolean = false;

    epistaxis?: boolean = false;

    familyHistoryOfBleedingDisorder?: number;

    motherCousin?: boolean = false;

    motherGrandfather?: boolean = false;

    motherGrandMother?: boolean = false;

    motherUncle?: boolean = false;

    motherAunt?: boolean = false;

    fatherCousin?: boolean = false;

    fatherGrandfather?: boolean = false;

    fatherGrandMother?: boolean = false;

    fatherUncle?: boolean = false;

    fatherAunt?: boolean = false;

    otherFamilyMembers?: number;

    familyHistoryOfDeathDueToBleeding?: number;

    historyOfAllergies?: number;

    historyOfAllergiesDetails?: string;

    patientId?: number;

    userId?: number;

    constructor(){
      this.toothOrGumBleeding= false;

      this.hematuria = false;

      this.gIbleeding = false;

      this.menorrhagia = false;

      this.bleedingAfterOperations = false;

      this.bleedingAfterTrauma = false;

      this.bleedingAtbirth = false;

      this.bleedingAfterVaccination = false;

      this.jointBleeding = false;

      this.skinBleeding = false;

      this.muscleBleeding = false;

      this.epistaxis = false;

      this.familyHistoryOfBleedingDisorder = 2;

      this.motherCousin = false;

      this.motherGrandfather = false;

      this.motherGrandMother = false;

      this.motherUncle = false;

      this.motherAunt = false;

      this.fatherCousin = false;

      this.fatherGrandfather = false;

      this.fatherGrandMother = false;

      this.fatherUncle = false;

      this.fatherAunt = false;

      this.otherFamilyMembers = 1;

      this.historyOfAllergies = 2;

    }

}
