/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Imaging {
    id?: number;

      imagingDate?: Date;

    imagingTypeId?: number;

    reading?: string;

    imagePaths?: any[];

    patientId?: number;

    userId?: number;

    constructor() {
      let date = new Date();
      this.imagingDate = date;
      this.imagePaths = [];
    }
}
