/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse200 {
    id?: number;

    patientUniqueCode?: string;

    name?: string;

    surName?: string;

    birthDate?: Date;

    birthPlace?: string;

    nationality?: string;

    parentalConsanguinity?: string;

    ageAtDignosis?: number;

    profession?: string;

    contactPhoneNumber?: string;

    numberOfBrothers?: number;

    deficientFactorLevel?: number;

    bloodGroup?: number;

    gender?: number;

    addressLine?: string;

    city?: string;

    state?: string;

    alley?: string;

    homeNumber?: string;

    educationalLevel?: number;

    schoolAttendance?: number;

    schoolPerformance?: number;

    fatherName?: string;

    fatherEducationLevel?: number;

    fatherProfession?: string;

    fatherContactNumber?: string;

    motherName?: string;

    motherEducationLevel?: number;

    motherProfession?: string;

    motherContactNumber?: string;

    nationalId?: number;

    userId?: number;

    hospitalId?: number;

    createdAt?: Date;

    updatedAt?: Date;

    deletedAt?: Date;

}
