/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Patient1 {
    id?: number;

    patientUniqueCode?: string;

    name?: string;

    birthDate?: Date;

    birthPlace?: string;

    nationality?: string;

    parentalConsanguinity?: number;

    ageAtDiagnosisNumber?: number;

    ageAtDiagnosisType?: string;

    ageAtOnsetOfBleedingNumber?: number;

    ageAtOnsetOfBleedingType?: string;

    profession?: string;

    contactPhoneNumber?: string;

    bloodGroup?: number;

    gender?: number;

    maritalStatus?: number;

    addressLine?: string;

    city?: string;

    state?: string;

    alley?: string;

    homeNumber?: string;

    educationalLevel?: number;

    schoolAttendance?: number;

    schoolPerformance?: number;

    employmentStatus?: number;

    diagnosis?: number;

    diagnosisTechnique?: number;

    bSLeftKnee?: boolean;

    bSRightKnee?: boolean;

    bSLeftAnkle?: boolean;

    bSRightAnkle?: boolean;

    bSLeftElbow?: boolean;

    bSRightElbow?: boolean;

    bSLeftShoulder?: boolean;

    bSRightShoulder?: boolean;

    bSLeftHip?: boolean;

    bSRightHip?: boolean;

    bSLeftWrist?: boolean;

    bSRightWrist?: boolean;

    bSIntracranial?: boolean;

    bSSpinalCord?: boolean;

    bSThroat?: boolean;

    bSGut?: boolean;

    bSMuscles?: boolean;

    bSOthers?: boolean;

    bleedingSeverity?: number;

    fatherName?: string;

    fatherEducationLevel?: number;

    fatherProfession?: string;

    fatherContactNumber?: string;

    motherName?: string;

    motherEducationLevel?: number;

    motherProfession?: string;

    motherContactNumber?: string;

    nationalId?: number;

    userId?: number;

    hospitalId?: number;

}
