/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    id?: number;

    name?: string;

    email?: string;

    username?: string;

    password?: string;

    rememberToken?: string;

    hospitalId?: number;

}
