/**
 * iHRegistry
 * iHRegistry APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Visit {
    id?: number;

    visitDate?: Date;

    weight?: number;

    height?: number;

    bloodPressureLow?: number;

    bloodPressureHigh?: number;

    heartRate?: number;

    temperature?: number;

    surgicalOperationProcedures?: boolean;

    dentalProcedures?: boolean;

    physiotherapyProcedures?: boolean;

    orthopedicProcedures?: boolean;

    labAssessmentsProcedures?: boolean;

    imagingProcedures?: boolean;

    transfusionLastVisit?: boolean;

    treatmentLastVisit?: boolean;

    complicationLastVisit?: number;

    patientId?: number;

    userId?: number;

    constructor(){
        this.surgicalOperationProcedures=false;
        this.dentalProcedures=false;
        this.physiotherapyProcedures=false;
        this.orthopedicProcedures=false;
        this.labAssessmentsProcedures=false;
        this.imagingProcedures=false;
        this.transfusionLastVisit=false;
        this.treatmentLastVisit=false;
    }

}
