/**
 * Virtual-Exposition-App APIs
 * Virtual-Exposition-App APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammed.elsayed.zaki@eye-ltd.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH }                                         from './variables';
import { Configuration }                                     from './configuration';
import {CustomHttp} from "app/services/CustomHttp";

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class EventStandApi {
    protected basePath = 'https://virtual-exposition-app-api.herokuapp.com/api/v1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: CustomHttp, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * update company
     * This can only be done by the logged in user.
     * @param companyData company data object
     * @param eventStandId company resource id
     */
    public reserveEventStand(companyData: models.Company, eventStandId: number, extraHttpRequestParams?: any): Observable<models.SuccessResponse> {
        return this.reserveEventStandWithHttpInfo(companyData, eventStandId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * update company
     * This can only be done by the logged in user.
     * @param companyData company data object
     * @param eventStandId company resource id
     */
    public reserveEventStandWithHttpInfo(companyData: models.Company, eventStandId: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/event-stand/${eventStandId}/reserve`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'companyData' is not null or undefined
        if (companyData === null || companyData === undefined) {
            throw new Error('Required parameter companyData was null or undefined when calling reserveEventStand.');
        }
        // verify required parameter 'eventStandId' is not null or undefined
        if (eventStandId === null || eventStandId === undefined) {
            throw new Error('Required parameter eventStandId was null or undefined when calling reserveEventStand.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
        // authentication (VirtualExposition_auth) required
        // oauth required
        if (this.configuration.accessToken)
        {
            headers.set('Authorization', 'Bearer ' + this.configuration.accessToken);
        }
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: companyData == null ? '' : JSON.stringify(companyData), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any> Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
